name: dsRID  # Change this to your preferred environment name
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - Bio=1.5.9
  - bioconda
  - biopython=1.80
  - numpy=1.23.5
  - pandas=1.5.3
  - pybedtools=0.9.0
  - pysam=0.18.0
  - scikit-learn=1.0.2
  - scipy=1.10.1
  - tpot=0.11.7
  - pip
  - pip:
      - Bio==1.5.9